# -*- coding: utf-8 -*-
"""Personal_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGQOyC5zUmAgNeBt8UTF1fUoL9luWeR-
"""

print("Hello World")

name=input("what is your name : ")
age=input("what is your age : ")
hobby=input("what is your favorite programing language : ")
education=input("what is your current education status : ")

print(f"""🎉 Hiii mr/mrs {name} !
            Welcome to our Personal introduction Program..
            you are {age} years old ,enjoy coding in {hobby} ,and are currently pursuing {education}.
            Thank you for sharing your details. Wishing you success and Happiness ahead.🙌🤗
            """)

